/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alfanumerico;

/**
 *
 * @author annelis
 */
public class swingAlfa extends javax.swing.JFrame {

    /**
     * Creates new form swingAlfa
     */
    public swingAlfa() {
        initComponents();
        //colocar al centro la ventana
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAviso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResultadoNum = new javax.swing.JTextArea();
        jButtonAccion = new javax.swing.JButton();
        jLabelVocal1 = new javax.swing.JLabel();
        jLabelVocal2 = new javax.swing.JLabel();
        jLabelVocal3 = new javax.swing.JLabel();
        jLabelVocal4 = new javax.swing.JLabel();
        jLabelVocal5 = new javax.swing.JLabel();
        jLabelNu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caracteres Alfanumericos");
        setBackground(new java.awt.Color(255, 51, 153));

        jLabelAviso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAviso.setText("Introduzca las palabras a evaluar");

        jTextAreaEntrada.setColumns(20);
        jTextAreaEntrada.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEntrada);

        jTextAreaResultadoNum.setColumns(20);
        jTextAreaResultadoNum.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResultadoNum);

        jButtonAccion.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAccion.setText("Resultado");

        jLabelVocal1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVocal1.setText("Palabras que tengan una vocal");

        jLabelVocal2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVocal2.setText("Palabras que tengan dos vocales");

        jLabelVocal3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVocal3.setText("Palabras que tengan tres vocales");

        jLabelVocal4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVocal4.setText("Palabras que tengan cuatro vocales");

        jLabelVocal5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVocal5.setText("Palabras que tengan cinco vocales");

        jLabelNu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNu.setText("Se muestra la posición de los números");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVocal2)
                            .addComponent(jLabelVocal1)
                            .addComponent(jLabelVocal3)
                            .addComponent(jLabelVocal4)
                            .addComponent(jLabelVocal5)
                            .addComponent(jLabelNu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAviso)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jButtonAccion)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelAviso)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabelVocal1)
                .addGap(12, 12, 12)
                .addComponent(jLabelVocal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelVocal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelVocal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelVocal5)
                .addGap(36, 36, 36)
                .addComponent(jLabelNu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(swingAlfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(swingAlfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(swingAlfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(swingAlfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new swingAlfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccion;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelNu;
    private javax.swing.JLabel jLabelVocal1;
    private javax.swing.JLabel jLabelVocal2;
    private javax.swing.JLabel jLabelVocal3;
    private javax.swing.JLabel jLabelVocal4;
    private javax.swing.JLabel jLabelVocal5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaEntrada;
    private javax.swing.JTextArea jTextAreaResultadoNum;
    // End of variables declaration//GEN-END:variables
}
